In [3]:
import torch
import torch.nn as nn
import numpy as np

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

# Define dataset
train_ds = TensorDataset(inputs, targets)

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

#Define model
model = nn.Linear(3,2)

#Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Import nn.functional
import torch.nn.functional as F

#Define loss function
loss_fn = F.mse_loss

#Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            #Generate predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
            #Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

#Train the model for 100 epochs
fit(100, model, loss_fn, opt)

#Generate predictions
preds = model(inputs)

Training loss:  tensor(26.1734, grad_fn=<MseLossBackward>)


In [4]:
model(inputs)

tensor([[ 58.5270,  71.7512],
        [ 80.4594,  98.3610],
        [120.9791, 136.3923],
        [ 28.0292,  44.5905],
        [ 94.8509, 110.6798],
        [ 58.5270,  71.7512],
        [ 80.4594,  98.3610],
        [120.9791, 136.3923],
        [ 28.0292,  44.5905],
        [ 94.8509, 110.6798],
        [ 58.5270,  71.7512],
        [ 80.4594,  98.3610],
        [120.9791, 136.3923],
        [ 28.0292,  44.5905],
        [ 94.8509, 110.6798]], grad_fn=<AddmmBackward>)

In [6]:
x1 = np.random.randint(1, 100, (1, 15)).reshape(-1, 1)
x2 = np.random.randint(1, 100, (1, 15)).reshape(-1, 1)
features = np.concatenate((x1, x2), 1)

In [9]:
targets = 3 * x1 + 2 * x2

In [8]:
features

array([[93, 17],
       [62,  5],
       [86, 12],
       [66,  5],
       [37, 54],
       [79, 91],
       [92, 62],
       [78, 18],
       [ 2, 49],
       [42, 19],
       [63, 78],
       [63, 44],
       [31,  8],
       [74, 30],
       [41, 28]])

In [11]:
import torch
import torch.nn as nn
import numpy as np

# Input (temp, rainfall, humidity)
# inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
inputs = features
# Targets (apples, oranges)
#targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
#                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
#                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

inputs = torch.tensor(inputs, dtype=torch.float32)
targets = torch.tensor(targets, dtype=torch.float32)

# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

# Define dataset
train_ds = TensorDataset(inputs, targets)

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

#Define model
model = nn.Linear(2, 1)

#Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Import nn.functional
import torch.nn.functional as F

#Define loss function
loss_fn = F.mse_loss

#Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            #Generate predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
            #Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

#Train the model for 100 epochs
fit(100, model, loss_fn, opt)

#Generate predictions
preds = model(inputs)

Training loss:  tensor(0.0415, grad_fn=<MseLossBackward>)


/var/folders/dz/nnw9rhd17_z5sf73fstryqhr0000gn/T/ipykernel_5631/3537288087.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets, dtype=torch.float32)


In [12]:
preds

tensor([[313.2637],
        [196.0826],
        [282.2311],
        [208.1116],
        [218.7235],
        [418.8936],
        [400.0931],
        [270.1513],
        [103.4880],
        [163.8868],
        [344.8248],
        [276.9482],
        [108.8470],
        [282.0788],
        [178.8469]], grad_fn=<AddmmBackward>)

In [13]:
targets

tensor([[313.],
        [196.],
        [282.],
        [208.],
        [219.],
        [419.],
        [400.],
        [270.],
        [104.],
        [164.],
        [345.],
        [277.],
        [109.],
        [282.],
        [179.]])